In [3]:
import pandas as pd
from pathlib import Path

In [12]:
ROOT_DIR = Path.cwd()
ss = ROOT_DIR/'data'/'superstoreSales.csv'
df = pd.read_csv(ss, encoding='latin1')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                232 non-null    int64
 1   Order ID              232 non-null    int64
 2   Order Date            232 non-null    str
 3   Order Priority        232 non-null    str
 4   Order Quantity        232 non-null    int64
 5   Sales                 232 non-null    float64
 6   Discount              232 non-null    float64
 7   Ship Mode             232 non-null    str
 8   Profit                232 non-null    float64
 9   Unit Price            232 non-null    float64
 10  Shipping Cost         232 non-null    float64
 11  Customer Name         232 non-null    str
 12  Province              232 non-null    str
 13  Region                232 non-null    str
 14  Customer Segment      232 non-null    str
 15  Product Category      232 non-null    str
 16  Product Sub-Category  232 non-null    str
 17  Product Name          232 non-null    str
 18  Product Container     232 non-null    str
 19  Product Base Margin   228 non-null    float64
 20  Ship Date             232 non-null    str
dtypes: float64(6), int64(3), str(12)
memory usage: 75.8 KB

Use named aggregation to get total, average, and count of Sales per Region in one call.

In [ ]:
grouped_df = df.groupby('Region').agg(total=('Sales', 'sum'), avg=('Sales', 'mean'), count=('Sales', 'count'))
grouped_df

                             total          avg  count
Region
Northwest Territories  354902.1545  2319.621925    153
Nunavut                116376.4835  1473.120044     79

Add a share_of_region column giving each order's fraction of its region's total sales (use
transform ).

In [13]:
df['share_of_region'] = df['Sales']/df.groupby('Region')['Sales'].transform('sum')
df

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date,share_of_region
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010,0.002247
1,49,293,10/1/2012,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,10/2/2012,0.086985
2,50,293,10/1/2012,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-Dï¿½ Ring Binder, Heavy Gauge V...",Small Box,0.39,10/3/2012,0.002102
3,80,483,7/10/2011,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,7/12/2011,0.042670
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010,0.003388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,3644,26051,6/27/2010,Not Specified,31,251.7500,0.07,Regular Air,22.46,8.33,...,Northwest Territories,Northwest Territories,Home Office,Technology,Computer Peripherals,"80 Minute Slim Jewel Case CD-R , 10/Pack - Sta...",Small Pack,0.52,6/28/2010,0.000709
228,3649,26116,10/29/2012,Critical,36,697.4100,0.04,Regular Air,81.71,18.97,...,Northwest Territories,Northwest Territories,Small Business,Office Supplies,Paper,Computer Printout Paper with Letter-Trim Perfo...,Small Box,0.37,10/30/2012,0.001965
229,3658,26182,1/16/2010,Not Specified,30,4684.9000,0.01,Delivery Truck,-549.27,150.98,...,Northwest Territories,Northwest Territories,Corporate,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,1/19/2010,0.013201
230,3666,26272,6/29/2012,Low,6,905.9400,0.04,Express Air,-4.19,140.81,...,Northwest Territories,Northwest Territories,Home Office,Furniture,Chairs & Chairmats,Hon Olson Stacker Stools,Large Box,0.57,7/8/2012,0.002553
231,3688,26370,8/8/2011,Not Specified,12,270.2300,0.08,Regular Air,52.02,22.84,...,Northwest Territories,Northwest Territories,Home Office,Office Supplies,Paper,Xerox 1929,Small Box,0.39,8/10/2011,0.000761

Keep only regions whose total sales exceed 1,000,000 (use filter ), and list which
survive.

I am using a subset of the data, none of the regions as a part of this data set have sales that surpass the requirement to show up

In [20]:
big_region = df.groupby('Region').filter(lambda x: x['Sales'].sum() > 1000000)
surving_region = big_region.groupby('Region')['Sales'].sum()
surving_region

Series([], Name: Sales, dtype: float64)

Find the top 3 orders by Sales within each Region

In [ ]:
top3 = (df.groupby('Region')).apply(lambda x: x.nlargest(3, 'Sales'))
top3

                           Row ID  Order ID  Order Date Order Priority  \
Region
Northwest Territories 200    3284     23488    1/6/2009       Critical
                      175    2624     19010    6/7/2009            Low
                      112    1727     12419  10/15/2011       Critical
Nunavut               39      440      2976   12/9/2010  Not Specified
                      27      250      1761  12/23/2010           High
                      1        49       293   10/1/2012           High

                           Order Quantity     Sales  Discount       Ship Mode  \
Region
Northwest Territories 200              30  26133.39      0.04  Delivery Truck
                      175              18  23792.93      0.00     Regular Air
                      112              12  22079.47      0.06     Regular Air
Nunavut               39               30  14223.82      0.09  Delivery Truck
                      27               25  12028.23      0.01  Delivery Truck
                      1                49  10123.02      0.07  Delivery Truck

                             Profit  Unit Price  ...    Customer Name  \
Region                                           ...
Northwest Territories 200 -11053.60      880.98  ...       Julia West
                      175  10951.31     1270.99  ...    Grant Carroll
                      112   5322.14     1938.02  ...  Sylvia Foulston
Nunavut               39    3424.22      500.98  ...     Edward Hooks
                      27    -547.61      449.99  ...      Carl Ludwig
                      1      457.81      208.16  ...     Barry French

                                        Province Customer Segment  \
Region
Northwest Territories 200  Northwest Territories      Home Office
                      175  Northwest Territories   Small Business
                      112  Northwest Territories        Corporate
Nunavut               39                 Nunavut         Consumer
                      27                 Nunavut        Corporate
                      1                  Nunavut         Consumer

                          Product Category            Product Sub-Category  \
Region
Northwest Territories 200        Furniture                       Bookcases
                      175  Office Supplies  Binders and Binder Accessories
                      112       Technology                 Office Machines
Nunavut               39         Furniture              Chairs & Chairmats
                      27        Technology                 Copiers and Fax
                      1    Office Supplies                      Appliances

                                                                Product Name  \
Region
Northwest Territories 200  Riverside Palais Royal Lawyers Bookcase, Royal...
                      175  Fellowes PB500 Electric Punch Plastic Comb Bin...
                      112  Polycom ViewStationï¿½ Adapter H323 Videoconfe...
Nunavut               39    Global Troyï¿½ Executive Leather Low-Back Tilter
                      27                                  Canon PC940 Copier
                      1    1.7 Cubic Foot Compact "Cube" Office Refrigera...

                          Product Container Product Base Margin   Ship Date  \
Region
Northwest Territories 200         Jumbo Box                0.62    1/7/2009
                      175         Small Box                0.35    6/9/2009
                      112        Medium Box                0.38  10/17/2011
Nunavut               39         Jumbo Drum                0.60  12/11/2010
                      27         Jumbo Drum                0.38  12/25/2010
                      1          Jumbo Drum                0.58   10/2/2012

                          share_of_region
Region
Northwest Territories 200        0.073635
                      175        0.067041
                      112        0.062213
Nunavut               39         0.122222
                      27         0.103356
                      1          0.086985

[6 rows x 21 columns]