In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
ROOT_DIR = Path.cwd()
ss = ROOT_DIR/'data'/'superstoreSales.csv'
customer = ROOT_DIR/'data'/'customers.csv'
orders = ROOT_DIR/'data'/'orders.csv'

dfc = pd.read_csv(customer)
dfo = pd.read_csv(orders)

Merge orders with customers using how="left" and indicator=True ; check whether any
orders had no matching customer.

In [ ]:
pd.merge(dfc, dfo, how='left', indicator=True)

,customer_id,name,city,segment,order_id,product,quantity,price,order_date,_merge
0,C001,Aisha Khan,Kathmandu,Consumer,O1001,Wireless Mouse,3,12.5,2024-01-15,both
1,C001,Aisha Khan,Kathmandu,Consumer,O1004,USB-C Cable,5,8.0,2024-02-11,both
2,C001,Aisha Khan,Kathmandu,Consumer,O1010,Monitor,1,220.0,2024-04-18,both
3,C002,Rajesh Sharma,Pokhara,Corporate,O1003,Laptop Stand,2,35.0,2024-02-03,both
4,C002,Rajesh Sharma,Pokhara,Corporate,O1008,Laptop Stand,1,35.0,2024-03-27,both
5,C002,Rajesh Sharma,Pokhara,Corporate,O1014,Desk Lamp,3,28.0,2024-06-15,both
6,C003,Maya Gurung,Lalitpur,Consumer,O1002,Office Chair,1,145.0,2024-01-22,both
7,C003,Maya Gurung,Lalitpur,Consumer,O1007,Desk Lamp,2,28.0,2024-03-14,both
8,C003,Maya Gurung,Lalitpur,Consumer,O1013,Keyboard,1,45.0,2024-06-01,both
9,C004,Bikash Thapa,Kathmandu,Home Office,O1005,Monitor,1,220.0,2024-02-19,both
10,C004,Bikash Thapa,Kathmandu,Home Office,O1012,USB-C Cable,3,8.0,2024-05-20,both
11,C005,Sunita Rai,Biratnagar,Corporate,O1006,Keyboard,4,45.0,2024-03-02,both
12,C005,Sunita Rai,Biratnagar,Corporate,O1011,Office Chair,2,145.0,2024-05-06,both
13,C006,Deepak Adhikari,Pokhara,Consumer,O1009,Wireless Mouse,2,12.5,2024-04-05,both
14,C006,Deepak Adhikari,Pokhara,Consumer,O1015,Monitor,1,220.0,2024-06-29,both

Re-run the merge with validate="many_to_one" and confirm it passes (many orders per
one customer)

In [ ]:

merged_df = pd.merge(dfc, dfo, how='left', indicator=True, validate='many_to_one')
merged_df

,customer_id,name,city,segment,order_id,product,quantity,price,order_date,_merge
0,C001,Aisha Khan,Kathmandu,Consumer,O1001,Wireless Mouse,3,12.5,2024-01-15,both
1,C002,Rajesh Sharma,Pokhara,Corporate,O1003,Laptop Stand,2,35.0,2024-02-03,both
2,C003,Maya Gurung,Lalitpur,Consumer,O1002,Office Chair,1,145.0,2024-01-22,both
3,C004,Bikash Thapa,Kathmandu,Home Office,O1005,Monitor,1,220.0,2024-02-19,both
4,C005,Sunita Rai,Biratnagar,Corporate,O1006,Keyboard,4,45.0,2024-03-02,both
5,C006,Deepak Adhikari,Pokhara,Consumer,O1009,Wireless Mouse,2,12.5,2024-04-05,both

Split customers into two halves and concat them back into one table.